ALTER TABLE  observation
  ADD FIELDWORKER VARCHAR(6) DEFAULT 'FWAD1',
  ADD processed_by_mirth VARCHAR(1) DEFAULT '0',
  ADD id INT AUTO_INCREMENT NOT NULL,
  ADD PRIMARY KEY (id);

ALTER TABLE observation ADD INDEX idx_observeid (OBSERVEID);

ALTER TABLE observation ADD INDEX idx_obslocation (LOCATIONID);
  
UPDATE observation set LOCATIONID=CONCAT(LEFT(LOCATIONID,3),'00',RIGHT(LOCATIONID,4));
UPDATE observation set OBSERVEID=CONCAT(LEFT(OBSERVEID,3),'000',RIGHT(OBSERVEID,6));
  

SELECT id, str_to_date(DATE,'%Y-%m-%d') DATE, OBSERVEID, LOCATIONID, FIELDWORKER, ROUND FROM observation WHERE processed_by_mirth=0;