ALTER TABLE pregoutcome
  ADD FIELDWORKER VARCHAR(6) DEFAULT 'FWAD1',
  ADD processed_by_mirth VARCHAR(1) DEFAULT '0',
  ADD id INT AUTO_INCREMENT NOT NULL,
  ADD PRIMARY KEY (id);

ALTER TABLE pregoutcome ADD INDEX idx_proind (INDIVIDID);
ALTER TABLE pregoutcome ADD INDEX idx_provis (OBSERVEID);

UPDATE pregoutcome set FATHERID='UNK' where FATHERID='Q';

UPDATE pregoutcome set INDIVIDID =CONCAT(LEFT(INDIVIDID,3),'00',RIGHT(INDIVIDID,7));
UPDATE pregoutcome set FATHERID =CONCAT(LEFT(FATHERID,3),'00',RIGHT(FATHERID,7)) where LENGTH(FATHERID)>6;

UPDATE pregoutcome set OBSERVEID=CONCAT(LEFT(OBSERVEID,3),'000',RIGHT(OBSERVEID,6));

SELECT id, OBSERVEID, INDIVIDID, 1 PARTIAL_DATE,FIELDWORKER,str_to_date(DATE,'%Y-%m-%d') DATE, FATHERID FROM pregoutcome WHERE processed_by_mirth =0;


