ALTER TABLE birth
  ADD FIELDWORKER VARCHAR(6) DEFAULT 'FWAD1',
  ADD processed_by_mirth VARCHAR(1) DEFAULT '0',
  ADD id INT AUTO_INCREMENT NOT NULL,
  ADD PRIMARY KEY (id);

UPDATE birth b, individual i set b.INDIVIDID=i.INDIVIDID where b.INDIVIDID=i.OLD_INDIVIDID;

UPDATE birth b, socialgroup s set b.SOCIALGPID=s.SOCIALGPID where b.SOCIALGPID=s.OLD_SOCIALGPID;

SELECT FIRSTNAME, TYPE, SOCIALGPID , GENDER, 9 RELATIONSHIP_TO_GROUP_HEAD, a.INDIVIDID INDIVIDID, LASTNAME FROM birth a, individual b where a.INDIVIDID = b.INDIVIDID LIMIT 1;
