ALTER TABLE death
  ADD FIELDWORKER VARCHAR(6) DEFAULT 'FWAD1',
  ADD processed_by_mirth VARCHAR(1) DEFAULT '0',
  ADD id INT AUTO_INCREMENT NOT NULL,
  ADD PRIMARY KEY (id);

ALTER TABLE death
 CHANGE DTHPLACE PLACE VARCHAR(99),
 CHANGE DTHCAUSE REASON VARCHAR(99);

update death set PLACE='UNK' where PLACE is null;
update death set REASON='UNK' where REASON is null;


UPDATE death d, individual i set d.INDIVIDID=i.INDIVIDID where d.INDIVIDID=i.OLD_INDIVIDID;
UPDATE death d, observation o set d.OBSERVEID=o.OBSERVEID where d.OBSERVEID=o.OLD_OBSERVEID;

SELECT id, OBSERVEID, REASON, FIELDWORKER, str_to_date(DATE,'%Y-%m-%d') DATE, PLACE, INDIVIDID FROM death where processed_by_mirth =0;
