ALTER TABLE death
  ADD FIELDWORKER VARCHAR(6) DEFAULT 'FWAD1',
  ADD processed_by_mirth VARCHAR(1) DEFAULT '0',
  ADD id INT AUTO_INCREMENT NOT NULL,
  ADD PRIMARY KEY (id);

ALTER TABLE death
 CHANGE DTHPLACE PLACE VARCHAR(99),
 CHANGE DTHCAUSE REASON VARCHAR(99);

update death set PLACE='UNK' where PLACE is null;
update death set REASON='UNK' where REASON is null;


UPDATE death set INDIVIDID =CONCAT(LEFT(INDIVIDID,3),'00',RIGHT(INDIVIDID,7));
UPDATE death set OBSERVEID=CONCAT(LEFT(OBSERVEID,3),'000',RIGHT(OBSERVEID,6));

SELECT id, OBSERVEID, REASON, FIELDWORKER, str_to_date(DATE,'%Y-%m-%d') DATE, PLACE, INDIVIDID FROM death where processed_by_mirth =0;