ALTER TABLE outmigration
  ADD FIELDWORKER VARCHAR(6) DEFAULT 'FWAD1',
  ADD processed_by_mirth VARCHAR(1) DEFAULT '0',
  ADD id INT AUTO_INCREMENT NOT NULL,
  ADD PRIMARY KEY (id);

ALTER TABLE outmigration ADD INDEX idx_omgind (INDIVIDID);
ALTER TABLE outmigration ADD INDEX idx_omgvis (OBSERVEID);

UPDATE outmigration set INDIVIDID =CONCAT(LEFT(INDIVIDID,3),'00',RIGHT(INDIVIDID,7));
UPDATE outmigration set OBSERVEID=CONCAT(LEFT(OBSERVEID,3),'000',RIGHT(OBSERVEID,6));

ALTER TABLE outmigration CHANGE OUTMGREASO REASON VARCHAR(99);


SELECT id, OBSERVEID, REGION_NAM, FIELDWORKER, str_to_date(DATE,'%Y-%m-%d') DATE, REASON, INDIVIDID FROM outmigration WHERE processed_by_mirth =0;



