ALTER TABLE inmigration
  ADD FIELDWORKER VARCHAR(6) DEFAULT 'FWAD1',
  ADD processed_by_mirth VARCHAR(1) DEFAULT '0',
  ADD id INT AUTO_INCREMENT NOT NULL,
  ADD PRIMARY KEY (id);

ALTER TABLE inmigration ADD INDEX idx_imgind (INDIVIDID);
ALTER TABLE inmigration ADD INDEX idx_imgvis (OBSERVEID);

ALTER TABLE inmigration CHANGE IMGREASON REASON VARCHAR(99);


update inmigration set REASON='OTHER' where REASON='6';

UPDATE inmigration set INDIVIDID =CONCAT(LEFT(INDIVIDID,3),'00',RIGHT(INDIVIDID,7));
UPDATE inmigration set OBSERVEID=CONCAT(LEFT(OBSERVEID,3),'000',RIGHT(OBSERVEID,6));



SELECT id, REASON, str_to_date(DATE,'%Y-%m-%d') DATE, INDIVIDID, REGION_NAM MOVED_FROM , OBSERVEID, INTERNAL, LOCATIONID, FIELDWORKER 
FROM inmigration where processed_by_mirth=0;




